pipeline {
    agent any
    
    environment{
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_KEY_ID')
    }
    
    parameters {
        choice(name: 'workspace', choices:['dev','prod'] )
        choice(name: 'action', choices:['apply','destroy'])
    }
    
    stages {
        stage('check') {
            steps {
                git branch: 'main', credentialsId: 'github-token', url: 'https://github.com/naghamahmed/RDS_REDIS_Nodejs_app.git'
            }
        }
        
        stage('terraform init') {
            steps {
                echo'----terraform-----'
                sh'terraform init'
                sh'terraform workspace new dev || true'
                sh'terraform workspace new prod || true'
            }
        }
        
        
        stage('terraform action') {  
            steps {
                echo"----${action}-----"
                sh"terraform workspace select ${workspace}"
                sh"terraform ${action} --auto-approve --var-file ${workspace}.tfvars "
            }
        }
    }
}
