pipeline {
    agent {
     label  'application' 
    }
    
    stages {
        
        stage('Git check') {
            steps {
                echo' -----GIT-----'
                git branch: 'rds_redis', credentialsId: 'github-token', url: 'https://github.com/naghamahmed/jenkins_nodejs_example.git'
            }
        }
        
        stage('dockerhub login') {
            steps {
                echo' -----DOCKERHUB-----'
                withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh"docker login -u $USERNAME -p $PASSWORD"
                    
                }
            }
        }
        
        
        stage('Build image') {  
            steps {
                echo'-----BUILD-----'
                sh 'docker build -t naghamahmed/nodejs_app .'
            }
        }
        
        stage('Run container') {
            environment {
                AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
                AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_KEY_ID')
                RDS_HOSTNAME   = '$(aws ssm get-parameter --name /dev/database/hostname --query "Parameter.Value" --with-decryption --output text)'
                RDS_PASSWORD   = '$(aws ssm get-parameter --name /dev/database/password --query "Parameter.Value" --with-decryption --output text)'
                REDIS_HOSTNAME = '$(aws ssm get-parameter --name /dev/redis/hostname --query "Parameter.Value" --with-decryption --output text)'
            }
            steps {
                echo'-----Container-----'
                sh" docker run -d -p 3000:3000 -e RDS_USERNAME=admin -e RDS_PASSWORD=${RDS_PASSWORD} -e RDS_HOSTNAME=${RDS_HOSTNAME} -e RDS_PORT=3306 -e REDIS_HOSTNAME=${REDIS_HOSTNAME} -e REDIS_PORT=6379 naghamahmed/nodejs_app"
            }
        } 
    }
}
